SELECT E1.EMPNO, E1.ENAME, E2.ENAME AS MANAGER, E2.EMPNO AS MGRNO FROM EMP E1, EMP E2 WHERE E1.MGR = E2.EMPNO;
SELECT ENAME, EMPNO, SAL FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');
SELECT NEXT_DAY(NEXT_DAY(TO_DATE('1 APR 2022', 'DD MON YYYY'), 'MONDAY'), 'MONDAY') FROM DUAL;
SELECT SYSDATE FROM DUAL;
SELECT ENAME, SAL, RPAD('*', SAL/1000, '*') FROM EMP;
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM > SAL + SAL * 0.05;
SELECT ENAME, JOB FROM EMP WHERE MGR IS NULL;

/*. Query to display Employee Number and Name for all employees who work in a 
department with any employee whose name contains a ‘T’*/
SELECT DISTINCT E1.EMPNO, E1.ENAME FROM EMP E1, EMP E2 WHERE E1.DEPTNO = E2.DEPTNO AND E2.ENAME LIKE '%T%';
SELECT E.EMPNO, E.ENAME, E.SAL, E.COMM FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND D.DNAME = 'SALES';
SELECT ENAME, SAL FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');
SELECT COUNT(DISTINCT E2.EMPNO) FROM EMP E1, EMP E2 WHERE E2.EMPNO = E1.MGR;
-- OR
SELECT COUNT(DISTINCT MGR) FROM EMP;
/*. Query to display Name, Job, Department No. and Department Name for all the 
employees working at the Dallas location.*/
SELECT E.ENAME, E.JOB, D.DEPTNO, D.DNAME FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND D.LOC = 'DALLAS';
SELECT DISTINCT JOB FROM EMP WHERE DEPTNO = 30;

SELECT E1.ENAME, E1.EMPNO, E2.ENAME AS MANAGER, E2.EMPNO AS MGRNO, E3.ENAME FROM EMP E1, EMP E2, EMP E3 WHERE E1.MGR = E2.EMPNO AND E3.MGR IS NULL;
SELECT ENAME FROM EMP WHERE MGR IS NULL;

/* Query to display Name, Department No. And Salary of any employee whose 
department No. and salary matches both the department no. And the salary of any 
employee who eans a commission.*/
